services:
  - type: web
    name: kauro-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BINANCE_API_KEY
        sync: true
      - key: BINANCE_SECRET_KEY
        sync: true
      - key: TELEGRAM_BOT_TOKEN
        sync: true
      - key: TELEGRAM_CHANNEL_ID
        sync: true
